services:
  - type: web
    name: remotion-hardstyle-shorts
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: CHROMIUM_PATH
        value: /usr/bin/google-chrome-stable
    healthCheckPath: /health
